permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 大风车
  email: warriorlious@gmail.com
  link: http://jennyprinter.com
  weibo: https://github.com/warriorlious/warriorlious.github.io
  github: https://github.com/warriorlious/warriorlious.github.io

# 站点信息
title: jennyprinter开源站点
description: jennyprinter
url: https://github.com/warriorlious/warriorlious.github.io
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: https://github.com/warriorlious/warriorlious.github.io

# disqus 设置
disqus:
  shortname: wl
